[package]
name = "glade"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tree-sitter.workspace = true
tree-sitter-rust.workspace = true

[lints]
workspace = true
