[package]
name = "backend-cpp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
backend-c-family = { path = "../backend-c-family" }
glade_core = { path = "../core" }
tree-sitter-cpp.workspace = true
tree-sitter-cuda.workspace = true

[lints]
workspace = true
